### ISSUE TITLE
Alaska no longer displayed

### ISSUE THREAD

**Issue by mbmc** [Siriolabs/Wings-of-the-Points#7]
Was removed in that [commit](https://github.com/Siriolabs/Wings-of-the-Points/commit/cbb2c24997a5e11a3ac134bec54d0b9459830d82).

**Comment by MartinGao** [comment]
Fixed. Thanks for your feedback.

**Comment by mbmc** [comment]
Wanted to make a PR, but not sure how you generated the ids.

**Comment by MartinGao** [comment]
I see. 

Indeed we have a database which stores all the data(airlines & ratios). Those ids are auto-generated. 
We put all related data to a JSON file (https://github.com/Siriolabs/Wings-of-the-Points/blob/master/local.json) therefore the web page can render the Wings chart.

If you found any incorrect / outdated info, just leave an issue here and we will reply ASAP.

Again, thanks for your support ! <3
